### ISSUE TITLE
Critical errors when updating Astra and Astra pro add-on

### ISSUE THREAD

**Issue by EricJammin** [brainstormforce/astra#1867]
### Describe the bug:
Updating the base astra theme triggers critical errors in the admin regarding the astra pro add-on, including this message:

Fatal error: Uncaught Error: Class 'Astra_Notices' not found in /site-url/wp-content/plugins/astra-addon/classes/class-astra-theme-extension.php:742 Stack trace: #0 /site-url/wp-includes/class-wp-hook.php(287): Astra_Theme_Extension->min_theme_version__error('') #1 /site-url/wp-includes/class-wp-hook.php(311): WP_Hook->apply_filters(NULL, Array) #2 /site-url/wp-includes/plugin.php(478): WP_Hook->do_action(Array) #3 /site-url/wp-admin/admin-header.php(281): do_action('admin_notices') #4 /site-url/wp-admin/update-core.php(739): require_once('/home/site-url/...') #5 {main} thrown in /site-url/wp-content/plugins/astra-addon/classes/class-astra-theme-extension.php on line 742
There has been a critical error on your website. Please check your site admin email inbox for instructions.

WP admin is not even usable as every tab displays that error message and nothing else.

### To reproduce:
1. Updating Astra theme to current version, before updating the Astra Pro add-on plugin.

### Expected behavior:
To still be able to use the WP admin. There should be a notice to update the pro add-on afterwards, it should not make the entire admin unusable.

### Isolating the problem:
Can not test with alternate theme or disabling other plugins, b/c the entire back-end is not usable.

### WordPress version:
5.4.2

### Astra Theme version:
2.5.4

**Comment by EricJammin** [comment]
I just deleted the old version of astra pro plugin, and uploaded the current version.

As soon as I activated it, I get the same critical error message. WP admin is unusable. This is ridiculous.

**Comment by EricJammin** [comment]
Updating to Wordpress v5.5 did not help.

**Comment by EricJammin** [comment]
Well, due to time restraints and deadlines, we ended up having to delete Astra, Astra Pro plugin, Elementor and Elementor Pro, and reinstalling all versions from downloads. 

Frankly I don't have time right now to keep looking into why this happened, but I will say this is not the first time we've seen critical errors get thrown by the Astra Pro plugin after updating the Astra theme. This really needs to be looked at, as it's making website maintenance on sites using Astra very burdensome.

Also curious why updating to new versions of Astra seems to reset any blank values in the Customizer back to the default ones (like colors, etc.), instead of respecting the empty values, but I suppose I can open a different ticket for that issue.

**Comment by premanshup** [comment]
@EricJammin Sorry for the inconvenience you have faced, with our latest update we have not received any issues regarding theme update causing a fatal error with Astra Pro and breaking the whole admin dashboard. 

Could you please open a support ticket from this link - https://wpastra.com/support/open-a-ticket/. We would require some login details which we can communicate over the ticket. This will help us debug the issue on your website.

**Comment by shubhw12** [comment]
Hello @EricJammin,

We haven't heard back from you in a while. Closing this due to lack of activity. Feel free to start a new thread if you're still experiencing the same on your end.
