### ISSUE TITLE
Bug Title ...

### ISSUE THREAD

**Issue by ptasz3k** [brainstormforce/astra#2846]
### Describe the bug:
Trying to customize page (via `wp-admin/customize.php?url=...` results in screen like presented in Screenshots section.

Wordpress log shows:

```
[08-Jun-2021 09:31:42 UTC] PHP Fatal error:  Uncaught Error: Class 'Astra_Control_Responsive_Color' not found in /usr/local/apache2/htdocs/wp-includes/class-wp-customize-manager.php:4121
Stack trace:
#0 /usr/local/apache2/htdocs/wp-includes/class-wp-hook.php(292): WP_Customize_Manager->render_control_templates()
#1 /usr/local/apache2/htdocs/wp-includes/class-wp-hook.php(316): WP_Hook->apply_filters()
#2 /usr/local/apache2/htdocs/wp-includes/plugin.php(484): WP_Hook->do_action()
#3 /usr/local/apache2/htdocs/wp-admin/customize.php(281): do_action()
#4 {main}
  thrown in /usr/local/apache2/htdocs/wp-includes/class-wp-customize-manager.php on line 4121
```

### To reproduce:
1. Go to page when logged in as admin.
2. Click on `Customize` (translated back from polish, i don't know if it is correct name). 

### Expected behavior:
Possibility to customize given page.

### Screenshots:

![obraz](https://user-images.githubusercontent.com/967266/121161404-3dcfd600-c84d-11eb-83a4-bd96293ea9f4.png)

### Isolating the problem:

- [ ] This bug happens with no other plugins activated
- [ ] This bug happens with a default WordPress theme active
- [x ] I can reproduce this bug consistently using the steps above

### WordPress version:
5.7.2

### Astra Theme version:
Astra 3.3.3
Astra Pro 4.2.1

**Comment by ptasz3k** [comment]
Problem fixed after upgrading Astra Pro to 3.5.0.
